server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Angular routing ke liye zaruri
    # Agar koi bhi route directly access kare toh index.html serve ho
    location / {
        try_files $uri $uri/ /index.html;
    }
}
